// This file is a placeholder for generated Supabase types.
// In a real application, this would be generated by the Supabase CLI.

export type Database = {
  public: {
    Tables: {
      repertoire: {
        Row: {
          id: string;
          title: string;
          artist: string;
          original_key: string | null;
          bpm: string | null;
          duration_seconds: number;
          // Add other necessary repertoire fields used in SetlistManager.tsx if needed,
          // but these cover the minimum required for the Song type definition.
        };
      };
    };
    // Add other schemas/tables if necessary, but repertoire is the one used here.
  };
};