// @ts-ignore: Deno runtime import
import { serve } from "https://deno.land/std@0.190.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { queries, mode = 'metadata' } = await req.json();
    console.log(`[AI Engine] Processing ${mode} for ${queries?.length || 0} items using Gemini 3 Flash Preview`);
    
    // @ts-ignore: Deno global
    const apiKey = Deno.env.get('GEMINI_API_KEY');

    if (!apiKey) {
      console.error("[AI Engine] Missing GEMINI_API_KEY environment variable");
      return new Response(JSON.stringify({ error: "AI Engine Configuration Missing: GEMINI_API_KEY not found" }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    let prompt = "";
    
    if (mode === 'lyrics') {
      const lyricsText = queries[0];
      prompt = `Act as a professional stage manager. Format these lyrics with double newlines between verses and proper punctuation for stage reading. Return ONLY a JSON object: {"lyrics": "formatted_lyrics_here"}.
      
      Lyrics:
      ${lyricsText}`;
    } else {
      const songsList = Array.isArray(queries) ? queries : [queries];
      prompt = `Act as a professional music librarian. For these songs, return a JSON array of objects. 
      Each object: {"name": "title", "artist": "primary artist", "originalKey": "standard key (C, F#m, etc)", "bpm": number, "genre": "genre", "ugUrl": "official ultimate guitar url", "isMetadataConfirmed": true}.
      
      Songs:
      ${songsList.join('\n')}
      
      Return ONLY the JSON array.`;
    }

    // Using gemini-3-flash-preview on v1beta endpoint as it's currently in preview
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=${apiKey}`;
    
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }]
      })
    });

    const result = await response.json();
    
    if (!response.ok) {
      console.error("[AI Engine] External API Error:", result);
      return new Response(JSON.stringify({ 
        error: `AI Provider Error: ${result.error?.message || response.statusText}`,
        details: result
      }), {
        status: response.status,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const text = result.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      console.error("[AI Engine] Empty candidates in response", result);
      throw new Error("No response generated by AI");
    }

    // Extract JSON from potential markdown wrappers
    const jsonMatch = text.match(/\{[\s\S]*\}|\[[\s\S]*\]/);
    if (!jsonMatch) {
      console.error("[AI Engine] No JSON found in text:", text);
      throw new Error("AI response was not in the expected format");
    }
    
    const output = JSON.parse(jsonMatch[0]);
    return new Response(JSON.stringify(output), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error("[AI Engine] Internal Handler Error:", error.message);
    return new Response(JSON.stringify({ 
      error: error.message,
      stack: error.stack
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
})