import SongAudioPlaybackTab from './SongAudioPlaybackTab';
import SongChartsTab from './SongChartsTab';
import SongConfigTab from './SongConfigTab';
import SongDetailsTab from './SongDetailsTab';
import SongStudioView from './SongStudioView';
import { SongSearch } from './SongSearch';
import SheetReaderHeader from './SheetReaderHeader';
import SheetReaderSidebar from './SheetReaderSidebar';
import SheetReaderAudioPlayer from './SheetReaderAudioPlayer';
import PerformanceOverlay from './PerformanceOverlay';
import FloatingCommandDock from './FloatingCommandDock';
import UserGuideModal from './UserGuideModal';
import AdminPanel from './AdminPanel';
import RepertoirePicker from './RepertoirePicker';
import ProSyncSearch from './ProSyncSearch';
import SetlistFilters, { FilterState, DEFAULT_FILTERS } from './SetlistFilters';
import SetlistExporter from './SetlistExporter';
import PublicRepertoireView from './PublicRepertoireView';
import SongTagManager from './SongTagManager';
import SongAssetMatrix from './SongAssetMatrix';
import SheetMusicRecommender from './SheetMusicRecommender';
import UGChordsEditor from './UGChordsEditor';
import UGChordsReader from './UGChordsReader';
import SearchHighlight from './SearchHighlight';
import CustomProgress from './CustomProgress';
import CustomSlider from './CustomSlider';
import SupportBanner from './SupportBanner';
import AuthProvider, { useAuth } from './AuthProvider';
import { useToneAudio, AudioEngineControls } from '@/hooks/use-tone-audio';
import { useReaderSettings, ReaderResourceForce } from '@/hooks/use-reader-settings';
import { useTheme } from '@/hooks/use-theme';
import { useKeyboardNavigation } from '@/hooks/use-keyboard-navigation';
import { useFollow } from '@/hooks/use-follow';
import { useSettings, GlobalSettings, KeyPreference } from '@/hooks/use-settings';
import { useSetlist } from '@/hooks/useSetlist';
import { useRepertoire } from '@/hooks/useRepertoire';
import { useToneAudio as useToneAudioHook } from '@/hooks/use-tone-audio';
import { useHarmonicSync } from '@/hooks/use-harmonic-sync';
import { useIsMobile } from '@/hooks/use-mobile';
import { supabase } from '@/integrations/supabase/client';
import { Database } from '@/lib/database.types';